# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oESTBkv-TbLO2hC3cF83k5lMqF9-CFXB
"""

import streamlit as st
import numpy as np
import os
import gdown
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image
from PIL import Image
import smtplib, ssl
from email.message import EmailMessage
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4
from reportlab.lib.utils import ImageReader
import datetime

# Google Drive .h5 model file ID (replace with yours)
file_id = '1kLZNlIa34pQ_ekedmN5UjXRpJD69F2lm'  # Replace with your real model file ID
model_path = 'BrainTumor.h5'

# Download model if not already present
if not os.path.exists(model_path):
    with st.spinner("🔄 Downloading model..."):
        gdown.download(f"https://drive.google.com/uc?id={file_id}", model_path, quiet=False)

# Load model
model = load_model(model_path)
st.success("✅ Model Loaded")

st.title("🧠 Brain Tumor Detection - Patient MRI Form")

with st.form("tumor_form"):
    name = st.text_input("👤 Patient Name", max_chars=50)
    email = st.text_input("📧 Email (to send report)")
    uploaded_file = st.file_uploader("🖼️ Upload Brain MRI Image", type=["jpg", "jpeg", "png"])
    submitted = st.form_submit_button("Submit")

if submitted and uploaded_file:
    img = Image.open(uploaded_file).convert("RGB")
    st.image(img, caption='Uploaded Image', use_column_width=True)

    # Preprocessing
    img_resized = img.resize((224, 224))
    img_array = image.img_to_array(img_resized)
    img_array = np.expand_dims(img_array, axis=0) / 255.0

    # Predict
    prediction = model.predict(img_array)[0][0]
    has_tumor = prediction >= 0.5

    # Diagnosis Result
    if has_tumor:
        result_text = "🚨 Tumor Detected"
        advice = (
            "MRI analysis suggests a possible brain tumor.\n"
            "Consult a neurologist or oncologist immediately.\n"
            "This is not a medical diagnosis."
        )
        st.error(result_text)
    else:
        result_text = "✅ No Tumor Detected"
        advice = (
            "No tumor found in the MRI scan.\n"
            "Maintain regular checkups and a healthy lifestyle.\n"
            "This is not a medical diagnosis."
        )
        st.success(result_text)

    # PDF Report
    img_path = "mri_image.jpg"
    img.save(img_path)

    pdf_path = "brain_tumor_report.pdf"
    c = canvas.Canvas(pdf_path, pagesize=A4)
    width, height = A4

    c.setFont("Helvetica-Bold", 18)
    c.drawCentredString(width / 2.0, height - 50, "🧠 Brain Tumor Detection Report")
    c.setFont("Helvetica", 12)
    c.drawString(50, height - 90, f"Name: {name}")
    c.drawString(50, height - 110, f"Date: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

    c.drawImage(ImageReader(img_path), 50, height - 350, width=200, height=200)
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, height - 370, "Result:")
    text = c.beginText(50, height - 390)
    text.setFont("Helvetica", 11)
    for line in advice.split("\n"):
        text.textLine(line)
    c.drawText(text)
    c.save()

    st.success("📄 Report generated!")

    # Email PDF
    if email.strip():
        sender_email = "p.thangaabirami@gmail.com"
        sender_password = "kbqj cubq nfzl aftg"
        receiver_email = email.strip()

        message = EmailMessage()
        message["From"] = sender_email
        message["To"] = receiver_email
        message["Subject"] = f"Brain Tumor Report - {name or 'Patient'}"
        message.set_content("Attached is your brain tumor detection report.")

        with open(pdf_path, "rb") as f:
            message.add_attachment(f.read(), maintype="application", subtype="pdf", filename="report.pdf")

        try:
            context = ssl.create_default_context()
            with smtplib.SMTP_SSL("smtp.gmail.com", 465, context=context) as server:
                server.login(sender_email, sender_password)
                server.send_message(message)
            st.success(f"📧 Report emailed to {receiver_email}")
        except Exception as e:
            st.error(f"❌ Email error: {e}")

!pip install streamlit

!pip install reportlab